version: '2'
services:

  mycustomapp:
    container_name: mycustomapp
    restart: always
    image: 2d0ff3c99185
    environment:
      MYSQL_PW: "${MYSQL_PW}"
      SESSION_SECRET: "${SESSION_SECRET}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "3002:${PORT}"